export const alexIpSeed = {
  positioning: {
    status: 'complete',
    role: '小姚哥｜创业过来人',
    positioning_statement: '帮本地生意老板诊断：钱漏在哪，人卡在哪。',
    monetization_goals: ['90天拿到至少10个付费1对1深度诊断客户'],
    acquisition_goals: ['通过内容→私信体检→1对1诊断获取高意向老板'],
    other_goals: ['沉淀老板经营诊断内容资产，跑通诊断到陪跑模型'],
    interview_answers: {},
    audiences: ['本地生意老板', '实体门店老板', '本地服务商', '小团队老板'],
    problems: ['引流、承接、成交、交付、复购链路断点', '定价、团队流程与利润结构不健康', '老板明知道要改却被心理和决策卡点困住'],
    pillars: ['老板真相与商业认知', '实战算账与案例经历', '创业感悟与经营工具'],
    source_refs: [{ type: 'profile_dossier', id: '01_定位与战略.md' }],
    version: 1,
    history: [],
  },
  profile: {
    role: '小姚哥｜创业过来人',
    audiences: ['本地生意老板', '实体门店老板', '本地服务商', '小团队老板'],
    problems: ['缺流量但更常见的是接不住流量', '员工、定价、活动和利润结构存在经营断点', '老板被侥幸、面子、沉没成本和不敢决策卡住'],
    pillars: ['老板真相与商业认知', '实战算账与案例经历', '创业感悟与经营工具'],
    viewpoints: ['老板不赚钱，通常不是一个点坏了，而是赚钱链路断了', '你不是缺流量，是接不住流量', '说重话可以，但要说准；戳痛点后必须给动作', '站在老板这边拆真相，不站上位教训人'],
    tone_preferences: ['犀利', '真实', '直接', '不装', '说真话', '短句', '先共鸣后诊断'],
    prohibited_patterns: ['不用你应该开头教训观众', '不只骂老板不给动作', '不做泛商业认知和代运营', '不暴露客户名称或未公开财务数据', '没有真实体感不装专家'],
    source_refs: [{ type: 'profile_dossier', id: '01_定位与战略.md' }],
    version: 1,
    history: [],
  },
}
